/**
 * SMS OTP integration — drop-in Express module.
 *
 * One-file core + per-provider adapters in ./providers/. Drop the whole `sms-otp/`
 * folder into any Node + Express project, add two lines in your server entry,
 * set env vars, done. See ./README.md for the full integration walkthrough.
 *
 * Endpoints registered by `mountSmsOtpRoutes(app)`:
 *   POST /api/sms-otp/send    body: { mobile }              -> sends a numeric OTP via the active provider
 *   POST /api/sms-otp/verify  body: { mobile, code }        -> verifies the OTP (one-shot, then consumed)
 *   GET  /api/sms-otp/health                                -> reports active provider + config + storage backend
 *
 * Active SMS provider via env: SMS_OTP_PROVIDER (default "msg91").
 * Register new providers in the PROVIDERS map below.
 *
 * Storage:
 *   - Firestore (collection "sms_otp_codes", doc id = 10-digit mobile) when Firebase Admin
 *     credentials are available (FIREBASE_SERVICE_ACCOUNT_JSON) and SMS_OTP_DISABLE_FIRESTORE!=1.
 *   - In-memory `Map` fallback otherwise. Per-process, non-durable.
 *
 * Peer dependencies (already standard in any Node 18+ / Express server):
 *   express                         required (mounting routes)
 *   firebase-admin                  optional (only needed for Firestore-backed storage)
 *
 * @typedef {object} SmsProviderSendInput
 * @property {string} mobile     10-digit Indian mobile (already normalised by the core).
 * @property {string} otp        Plaintext OTP code generated by the core.
 * @property {number} otpLength  Number of digits in `otp`.
 *
 * @typedef {object} SmsProviderSendResult
 * @property {boolean} ok
 * @property {number}  [status]      HTTP status from the provider's API.
 * @property {string}  [request_id]  Provider's tracking id (for support tickets).
 * @property {string}  [error]       Human-readable error message (only when ok=false).
 *
 * @typedef {object} SmsProvider
 * @property {string} name
 * @property {(input: SmsProviderSendInput) => Promise<SmsProviderSendResult>} sendOtp
 * @property {() => string[]} missingEnvKeys
 * @property {() => Record<string, unknown>} debugInfo
 */

import crypto from "node:crypto";
import express from "express";
import { provider as msg91Provider } from "./providers/msg91.mjs";

/** Provider registry. Add new providers here once their adapter file exists. */
const PROVIDERS = {
    msg91: msg91Provider
};

const DEFAULT_PROVIDER_NAME = "msg91";
const LOG_TAG = "[sms-otp]";

function activeProviderName_() {
    const raw = (process.env.SMS_OTP_PROVIDER || DEFAULT_PROVIDER_NAME).trim().toLowerCase();
    return PROVIDERS[raw] ? raw : DEFAULT_PROVIDER_NAME;
}

function activeProvider_() {
    return PROVIDERS[activeProviderName_()];
}

function envInt_(key, fallback, min, max) {
    const raw = (process.env[key] || "").trim();
    if (!raw) {
        return fallback;
    }
    const n = Number(raw);
    if (!Number.isFinite(n)) {
        return fallback;
    }
    const clamped = Math.round(n);
    if (Number.isFinite(min) && clamped < min) {
        return min;
    }
    if (Number.isFinite(max) && clamped > max) {
        return max;
    }
    return clamped;
}

function smsOtpLength_() {
    return envInt_("SMS_OTP_LENGTH", 6, 4, 8);
}

function smsOtpTtlSeconds_() {
    return envInt_("SMS_OTP_TTL_SECONDS", 300, 30, 15 * 60);
}

function smsOtpMaxAttempts_() {
    return envInt_("SMS_OTP_MAX_ATTEMPTS", 5, 1, 20);
}

function smsOtpResendCooldownSeconds_() {
    return envInt_("SMS_OTP_RESEND_COOLDOWN_S", 30, 0, 600);
}

function smsOtpIpLimit_() {
    return envInt_("SMS_OTP_IP_LIMIT", 10, 1, 200);
}

function smsOtpIpWindowSeconds_() {
    return envInt_("SMS_OTP_IP_WINDOW_S", 600, 60, 3600);
}

function smsOtpFirestoreEnabled_() {
    return process.env.SMS_OTP_DISABLE_FIRESTORE !== "1";
}

function smsOtpAuditEnabled_() {
    return process.env.SMS_OTP_AUDIT_TO_FIRESTORE === "1";
}

function smsOtpFirestoreCollection_() {
    return (process.env.SMS_OTP_FIRESTORE_COLLECTION || "sms_otp_codes").trim() || "sms_otp_codes";
}

function smsOtpAuditCollection_() {
    return (process.env.SMS_OTP_AUDIT_COLLECTION || "sms_otp_audit").trim() || "sms_otp_audit";
}

/** Cryptographically-strong numeric OTP of `SMS_OTP_LENGTH` digits. */
function generateOtp_() {
    const len = smsOtpLength_();
    let out = "";
    while (out.length < len) {
        const buf = crypto.randomBytes(len);
        for (let i = 0; i < buf.length && out.length < len; i += 1) {
            out += String(buf[i] % 10);
        }
    }
    return out;
}

function sha256Hex_(s) {
    return crypto.createHash("sha256").update(String(s)).digest("hex");
}

/** Strip +91 / 91 / leading 0; return 10-digit Indian mobile or "" if invalid. */
function normalizeIndianMobile_(raw) {
    const digits = String(raw == null ? "" : raw).replace(/\D+/g, "");
    let d = digits;
    if (d.length === 12 && d.startsWith("91")) {
        d = d.slice(2);
    } else if (d.length === 11 && d.startsWith("0")) {
        d = d.slice(1);
    }
    if (!/^[6-9]\d{9}$/.test(d)) {
        return "";
    }
    return d;
}

/** "9999999999" -> "******9999" (mobile-PII masking for logs). */
function maskMobile_(m) {
    const s = String(m == null ? "" : m);
    if (s.length <= 4) {
        return "*".repeat(Math.max(0, s.length));
    }
    return "*".repeat(s.length - 4) + s.slice(-4);
}

/** Structured JSON log line, prefixed with `[sms-otp]` for easy grep in deployment logs. */
function log_(event, fields) {
    try {
        const line = { tag: LOG_TAG.replace(/[\[\]]/g, ""), event, ...fields };
        console.log(`${LOG_TAG} ${JSON.stringify(line)}`);
    } catch {
        /* ignore log failures */
    }
}

// ---------------------------------------------------------------------------
// Firebase Admin — self-contained init (works whether or not the host app
// already initialised firebase-admin)
// ---------------------------------------------------------------------------

/**
 * @type {null | typeof import("firebase-admin")} Lazily-loaded firebase-admin module.
 *   `null` until first probe; `undefined`-equivalent ({}) if the package isn't installed.
 */
let firebaseAdminMod_ = null;
let firebaseAdminProbed_ = false;

async function loadFirebaseAdmin_() {
    if (firebaseAdminProbed_) {
        return firebaseAdminMod_;
    }
    firebaseAdminProbed_ = true;
    try {
        const mod = await import("firebase-admin");
        firebaseAdminMod_ = mod && mod.default ? mod.default : mod;
    } catch {
        firebaseAdminMod_ = null;
    }
    return firebaseAdminMod_;
}

async function ensureFirebaseInited_() {
    const admin = await loadFirebaseAdmin_();
    if (!admin || !admin.apps) {
        return null;
    }
    if (admin.apps.length) {
        return admin;
    }
    const json = (process.env.FIREBASE_CONFIG || process.env.FIREBASE_SERVICE_ACCOUNT_JSON || "").trim();
    if (!json) {
        return null;
    }
    try {
        const cred = JSON.parse(json);
        const dbUrl = (process.env.FIREBASE_DATABASE_URL || "").trim();
        admin.initializeApp({
            credential: admin.credential.cert(cred),
            projectId: cred.project_id,
            ...(dbUrl ? { databaseURL: dbUrl } : {})
        });
        return admin;
    } catch (e) {
        log_("firebase_init_failed", { error: e && e.message ? e.message : String(e) });
        return null;
    }
}

// ---------------------------------------------------------------------------
// Storage: Firestore-backed with graceful in-memory fallback
// ---------------------------------------------------------------------------

/** @type {Map<string, { codeHash: string, expiresAt: number, attempts: number, sentAt: number, requestId?: string }>} */
const memoryStore = new Map();

/** @type {null | { db: any, admin: any }} */
let firestoreCtx_ = null;
let firestoreProbed_ = false;

function purgeExpiredMemoryOtps_() {
    const now = Date.now();
    for (const [key, rec] of memoryStore.entries()) {
        if (!rec || rec.expiresAt <= now) {
            memoryStore.delete(key);
        }
    }
}

async function getFirestoreCtx_() {
    if (firestoreProbed_) {
        return firestoreCtx_;
    }
    firestoreProbed_ = true;
    if (!smsOtpFirestoreEnabled_()) {
        firestoreCtx_ = null;
        log_("storage_backend_selected", { backend: "memory", reason: "SMS_OTP_DISABLE_FIRESTORE=1" });
        return null;
    }
    const admin = await ensureFirebaseInited_();
    if (!admin) {
        firestoreCtx_ = null;
        log_("storage_backend_selected", {
            backend: "memory",
            reason: "firebase-admin not available or not configured"
        });
        return null;
    }
    try {
        const db = admin.firestore();
        firestoreCtx_ = { db, admin };
        log_("storage_backend_selected", {
            backend: "firestore",
            collection: smsOtpFirestoreCollection_()
        });
        return firestoreCtx_;
    } catch (e) {
        firestoreCtx_ = null;
        log_("firestore_get_failed", { error: e && e.message ? e.message : String(e) });
        return null;
    }
}

async function storeOtp_(mobile, code, requestId) {
    const ttlMs = smsOtpTtlSeconds_() * 1000;
    const expiresAt = Date.now() + ttlMs;
    const record = {
        codeHash: sha256Hex_(code),
        expiresAt,
        attempts: 0,
        sentAt: Date.now(),
        requestId: requestId || ""
    };
    const ctx = await getFirestoreCtx_();
    if (ctx) {
        await ctx.db.collection(smsOtpFirestoreCollection_()).doc(mobile).set({
            codeHash: record.codeHash,
            expires_at_ms: record.expiresAt,
            attempts: 0,
            sent_at_ms: record.sentAt,
            request_id: record.requestId,
            created_at: ctx.admin.firestore.FieldValue.serverTimestamp()
        });
        return;
    }
    purgeExpiredMemoryOtps_();
    memoryStore.set(mobile, record);
}

async function readOtp_(mobile) {
    const ctx = await getFirestoreCtx_();
    if (ctx) {
        const snap = await ctx.db.collection(smsOtpFirestoreCollection_()).doc(mobile).get();
        if (!snap.exists) {
            return null;
        }
        const v = snap.data() || {};
        const rec = {
            codeHash: typeof v.codeHash === "string" ? v.codeHash : "",
            expiresAt: Number.isFinite(v.expires_at_ms) ? Number(v.expires_at_ms) : 0,
            attempts: Number.isFinite(v.attempts) ? Number(v.attempts) : 0,
            sentAt: Number.isFinite(v.sent_at_ms) ? Number(v.sent_at_ms) : 0,
            requestId: typeof v.request_id === "string" ? v.request_id : ""
        };
        if (!rec.codeHash || rec.expiresAt <= Date.now()) {
            try {
                await ctx.db.collection(smsOtpFirestoreCollection_()).doc(mobile).delete();
            } catch {
                /* best effort */
            }
            return null;
        }
        return rec;
    }
    purgeExpiredMemoryOtps_();
    const rec = memoryStore.get(mobile);
    if (!rec || rec.expiresAt <= Date.now()) {
        if (rec) {
            memoryStore.delete(mobile);
        }
        return null;
    }
    return { ...rec };
}

async function incrementAttempts_(mobile, newAttempts) {
    const ctx = await getFirestoreCtx_();
    if (ctx) {
        await ctx.db.collection(smsOtpFirestoreCollection_()).doc(mobile).update({
            attempts: newAttempts
        });
        return;
    }
    const rec = memoryStore.get(mobile);
    if (rec) {
        rec.attempts = newAttempts;
    }
}

async function deleteOtp_(mobile) {
    const ctx = await getFirestoreCtx_();
    if (ctx) {
        try {
            await ctx.db.collection(smsOtpFirestoreCollection_()).doc(mobile).delete();
        } catch {
            /* best effort */
        }
        return;
    }
    memoryStore.delete(mobile);
}

async function consumeOtp_(mobile, code) {
    const rec = await readOtp_(mobile);
    if (!rec) {
        return { ok: false, reason: "no_otp_or_expired" };
    }
    const max = smsOtpMaxAttempts_();
    if (rec.attempts >= max) {
        await deleteOtp_(mobile);
        return { ok: false, reason: "too_many_attempts" };
    }
    const nextAttempts = rec.attempts + 1;
    if (rec.codeHash !== sha256Hex_(code)) {
        const remaining = Math.max(0, max - nextAttempts);
        if (remaining <= 0) {
            await deleteOtp_(mobile);
            return { ok: false, reason: "too_many_attempts", attempts_remaining: 0 };
        }
        await incrementAttempts_(mobile, nextAttempts);
        return { ok: false, reason: "invalid_code", attempts_remaining: remaining };
    }
    await deleteOtp_(mobile);
    return { ok: true };
}

// ---------------------------------------------------------------------------
// Per-IP rate limiting (in-memory, per-instance)
// ---------------------------------------------------------------------------

/** @type {Map<string, number[]>} */
const ipSendTimestamps = new Map();

function recordIpSend_(ip) {
    if (!ip) {
        return { allowed: true, remaining: smsOtpIpLimit_() };
    }
    const now = Date.now();
    const windowMs = smsOtpIpWindowSeconds_() * 1000;
    const limit = smsOtpIpLimit_();
    const arr = ipSendTimestamps.get(ip) || [];
    const fresh = arr.filter((t) => now - t < windowMs);
    if (fresh.length >= limit) {
        ipSendTimestamps.set(ip, fresh);
        const oldest = fresh[0];
        const retryAfter = Math.max(1, Math.ceil((windowMs - (now - oldest)) / 1000));
        return { allowed: false, remaining: 0, retry_after_seconds: retryAfter };
    }
    fresh.push(now);
    ipSendTimestamps.set(ip, fresh);
    return { allowed: true, remaining: limit - fresh.length };
}

function pruneIpStoreIfLarge_() {
    if (ipSendTimestamps.size < 5000) {
        return;
    }
    const now = Date.now();
    const windowMs = smsOtpIpWindowSeconds_() * 1000;
    for (const [ip, arr] of ipSendTimestamps.entries()) {
        const fresh = arr.filter((t) => now - t < windowMs);
        if (fresh.length === 0) {
            ipSendTimestamps.delete(ip);
        } else {
            ipSendTimestamps.set(ip, fresh);
        }
    }
}

// ---------------------------------------------------------------------------
// Audit trail (optional Firestore writes)
// ---------------------------------------------------------------------------

function auditLog_(event, fields) {
    if (!smsOtpAuditEnabled_()) {
        return;
    }
    /** Fire-and-forget: do not block the response on audit writes. */
    (async () => {
        try {
            const ctx = await getFirestoreCtx_();
            if (!ctx) {
                return;
            }
            await ctx.db.collection(smsOtpAuditCollection_()).add({
                event,
                provider: activeProviderName_(),
                ...fields,
                created_at: ctx.admin.firestore.FieldValue.serverTimestamp()
            });
        } catch (e) {
            log_("audit_write_failed", { error: e && e.message ? e.message : String(e) });
        }
    })();
}

// ---------------------------------------------------------------------------
// HTTP handlers
// ---------------------------------------------------------------------------

function clientIp_(req) {
    return (req && typeof req.ip === "string" && req.ip) || "";
}

/** POST /api/sms-otp/send */
async function handleSendOtp_(req, res) {
    const ip = clientIp_(req);
    const providerName = activeProviderName_();
    try {
        const body = req.body && typeof req.body === "object" ? req.body : {};
        const mobile = normalizeIndianMobile_(body.mobile);
        if (!mobile) {
            log_("send_rejected_bad_mobile", { ip, provider: providerName });
            return res
                .status(400)
                .json({ ok: false, error: "Provide a valid 10-digit Indian mobile number." });
        }

        pruneIpStoreIfLarge_();
        const ipCheck = recordIpSend_(ip);
        if (!ipCheck.allowed) {
            log_("send_rejected_ip_rate_limit", {
                ip,
                provider: providerName,
                mobile_masked: maskMobile_(mobile),
                retry_after_seconds: ipCheck.retry_after_seconds
            });
            auditLog_("send_blocked_ip", {
                mobile_masked: maskMobile_(mobile),
                ip,
                retry_after_seconds: ipCheck.retry_after_seconds
            });
            return res
                .status(429)
                .set("Retry-After", String(ipCheck.retry_after_seconds))
                .json({
                    ok: false,
                    error: `Too many OTP requests from this network. Try again in ${ipCheck.retry_after_seconds}s.`,
                    retry_after_seconds: ipCheck.retry_after_seconds,
                    reason: "ip_rate_limited"
                });
        }

        const cooldown = smsOtpResendCooldownSeconds_();
        if (cooldown > 0) {
            const existing = await readOtp_(mobile);
            if (existing && Number.isFinite(existing.sentAt)) {
                const elapsedMs = Date.now() - existing.sentAt;
                const remainingMs = cooldown * 1000 - elapsedMs;
                if (remainingMs > 0) {
                    const retryAfter = Math.ceil(remainingMs / 1000);
                    log_("send_rejected_cooldown", {
                        ip,
                        provider: providerName,
                        mobile_masked: maskMobile_(mobile),
                        retry_after_seconds: retryAfter
                    });
                    return res
                        .status(429)
                        .set("Retry-After", String(retryAfter))
                        .json({
                            ok: false,
                            error: `Please wait ${retryAfter}s before requesting a new OTP.`,
                            retry_after_seconds: retryAfter,
                            reason: "cooldown"
                        });
                }
            }
        }

        const provider = activeProvider_();
        const otp = generateOtp_();
        const sendResult = await provider.sendOtp({
            mobile,
            otp,
            otpLength: smsOtpLength_()
        });
        if (!sendResult.ok) {
            log_("send_failed_provider", {
                ip,
                provider: providerName,
                mobile_masked: maskMobile_(mobile),
                provider_status: sendResult.status,
                error: sendResult.error
            });
            auditLog_("send_failed", {
                mobile_masked: maskMobile_(mobile),
                ip,
                provider_status: sendResult.status,
                error: sendResult.error
            });
            return res
                .status(502)
                .json({ ok: false, error: sendResult.error || "Failed to send OTP." });
        }

        await storeOtp_(mobile, otp, sendResult.request_id);
        log_("send_ok", {
            ip,
            provider: providerName,
            mobile_masked: maskMobile_(mobile),
            request_id: sendResult.request_id
        });
        auditLog_("send_ok", {
            mobile_masked: maskMobile_(mobile),
            ip,
            request_id: sendResult.request_id
        });

        return res.status(200).json({
            ok: true,
            message: "OTP sent.",
            ttl_seconds: smsOtpTtlSeconds_(),
            request_id: sendResult.request_id
        });
    } catch (e) {
        const msg = e && e.message ? e.message : String(e);
        log_("send_exception", { ip, provider: providerName, error: msg });
        return res.status(500).json({ ok: false, error: msg });
    }
}

/** POST /api/sms-otp/verify */
async function handleVerifyOtp_(req, res) {
    const ip = clientIp_(req);
    try {
        const body = req.body && typeof req.body === "object" ? req.body : {};
        const mobile = normalizeIndianMobile_(body.mobile);
        const codeRaw = body.code != null ? body.code : body.otp;
        const code = String(codeRaw == null ? "" : codeRaw).replace(/\D+/g, "");
        if (!mobile) {
            return res
                .status(400)
                .json({ ok: false, error: "Provide a valid 10-digit Indian mobile number." });
        }
        if (!code) {
            return res.status(400).json({ ok: false, error: "Provide the OTP code." });
        }
        const r = await consumeOtp_(mobile, code);
        if (r.ok) {
            log_("verify_ok", { ip, mobile_masked: maskMobile_(mobile) });
            auditLog_("verify_ok", { mobile_masked: maskMobile_(mobile), ip });
            return res.status(200).json({ ok: true, message: "OTP verified." });
        }
        let httpStatus = 400;
        let message = "Invalid or expired OTP.";
        if (r.reason === "no_otp_or_expired") {
            message = "OTP expired or not requested. Please request a new code.";
            httpStatus = 410;
        } else if (r.reason === "too_many_attempts") {
            message = "Too many incorrect attempts. Please request a new OTP.";
            httpStatus = 429;
        } else if (r.reason === "invalid_code") {
            message = "Incorrect OTP.";
            httpStatus = 400;
        }
        log_("verify_failed", {
            ip,
            mobile_masked: maskMobile_(mobile),
            reason: r.reason,
            attempts_remaining: r.attempts_remaining
        });
        auditLog_("verify_failed", {
            mobile_masked: maskMobile_(mobile),
            ip,
            reason: r.reason,
            attempts_remaining: r.attempts_remaining
        });
        return res.status(httpStatus).json({
            ok: false,
            error: message,
            reason: r.reason,
            attempts_remaining: r.attempts_remaining
        });
    } catch (e) {
        const msg = e && e.message ? e.message : String(e);
        log_("verify_exception", { ip, error: msg });
        return res.status(500).json({ ok: false, error: msg });
    }
}

/** GET /api/sms-otp/health */
async function handleHealth_(_req, res) {
    const providerName = activeProviderName_();
    const provider = activeProvider_();
    const missingEnv = typeof provider.missingEnvKeys === "function" ? provider.missingEnvKeys() : [];
    const providerDebug = typeof provider.debugInfo === "function" ? provider.debugInfo() : {};
    const ctx = await getFirestoreCtx_();
    return res.status(200).json({
        ok: missingEnv.length === 0,
        provider: providerName,
        provider_ready: missingEnv.length === 0,
        provider_missing_env: missingEnv,
        provider_info: providerDebug,
        available_providers: Object.keys(PROVIDERS),
        otp_length: smsOtpLength_(),
        ttl_seconds: smsOtpTtlSeconds_(),
        max_attempts: smsOtpMaxAttempts_(),
        resend_cooldown_seconds: smsOtpResendCooldownSeconds_(),
        ip_limit: smsOtpIpLimit_(),
        ip_window_seconds: smsOtpIpWindowSeconds_(),
        storage_backend: ctx ? "firestore" : "memory",
        firestore_collection: ctx ? smsOtpFirestoreCollection_() : null,
        audit_enabled: smsOtpAuditEnabled_(),
        audit_collection: smsOtpAuditEnabled_() ? smsOtpAuditCollection_() : null,
        memory_pending_count: memoryStore.size,
        ip_tracker_size: ipSendTimestamps.size
    });
}

/**
 * Register SMS OTP routes on the given Express app.
 * Call once after `const app = express();`.
 * @param {import("express").Express} app
 */
export function mountSmsOtpRoutes(app) {
    /** Required so `req.ip` reflects the visitor's IP behind any edge proxy (X-Forwarded-For). */
    if (typeof app.set === "function") {
        const current = typeof app.get === "function" ? app.get("trust proxy") : undefined;
        if (current === undefined || current === false || current === 0) {
            app.set("trust proxy", true);
        }
    }

    const json = express.json({ limit: "16kb" });
    app.post("/api/sms-otp/send", json, handleSendOtp_);
    app.post("/api/sms-otp/verify", json, handleVerifyOtp_);
    app.get("/api/sms-otp/health", handleHealth_);
}

/** Exposed for unit testing only. */
export const __smsOtpInternals = {
    normalizeIndianMobile: normalizeIndianMobile_,
    maskMobile: maskMobile_,
    generateOtp: generateOtp_,
    storeOtp: storeOtp_,
    readOtp: readOtp_,
    consumeOtp: consumeOtp_,
    recordIpSend: recordIpSend_,
    activeProvider: activeProvider_,
    PROVIDERS,
    memoryStore,
    ipSendTimestamps
};
